server:
  port: 8080
  # ? ??????? ??? ? ??
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /
  # ?? ??? ????? ???? ?? Whitelabel Error Page ?? OFF
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        highlight_sql: true
        show-sql: true